# Generated by Django 4.2.28 on 2026-02-12 06:31

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 7), ('about', 9), ('services', 14), ('faq', 17), ('testimonials', 20), ('cta', 22), ('gallery', 25)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('v1', 'Variant 1'), ('v2', 'Variant 2'), ('v3', 'Variant 3')], 'help_text': 'Select the layout variant for this block.'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('fade-left', 'Fade Left'), ('fade-right', 'Fade Right'), ('zoom-in', 'Zoom In')], 'help_text': 'Select the AOS animation effect.'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('image', 4), ('cta_text', 5), ('cta_link', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('content', 8), ('image', 4)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon name (e.g. from FontAwesome or similar)', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('icon', 10), ('name', 2), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('services', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 8)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('items', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('quote', 11), ('author', 2), ('role', 5), ('image', 4)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('testimonials', 19)]], {}), 21: ('wagtail.blocks.URLBlock', (), {'required': True}), 22: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('button_text', 2), ('button_link', 21)]], {}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('images', 24)]], {})})),
            ],
            options={
                'verbose_name': 'Content Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_theme', models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('bold', 'Bold')], default='modern', max_length=20)),
                ('hero_variant', models.CharField(default='v1', max_length=10)),
                ('about_variant', models.CharField(default='v1', max_length=10)),
                ('services_variant', models.CharField(default='v1', max_length=10)),
                ('faq_variant', models.CharField(default='v1', max_length=10)),
                ('primary_color', models.CharField(default='#6C63FF', max_length=7)),
                ('secondary_color', models.CharField(default='#FF6584', max_length=7)),
                ('background_color', models.CharField(default='#0F172A', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('heading_font', models.CharField(default='Poppins', max_length=100)),
                ('body_font', models.CharField(default='Inter', max_length=100)),
                ('animation_preset', models.CharField(default='smooth-fade', max_length=50)),
                ('last_ai_prompt', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Theme Configuration',
                'verbose_name_plural': 'Theme Configuration',
            },
        ),
    ]
