# Generated by Django 4.2.28 on 2026-02-12 07:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.forms.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, validators=[wagtail.contrib.forms.models.validate_to_address], verbose_name='to address')),
                ('from_address', models.EmailField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('intro', wagtail.fields.StreamField([('hero', 7)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('v1', 'Variant 1'), ('v2', 'Variant 2'), ('v3', 'Variant 3')], 'help_text': 'Select the layout variant for this block.'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('fade-left', 'Fade Left'), ('fade-right', 'Fade Right'), ('zoom-in', 'Zoom In')], 'help_text': 'Select the AOS animation effect.'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('image', 4), ('cta_text', 5), ('cta_link', 6)]], {})})),
                ('thank_you_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contentpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('about', 9), ('services', 14), ('faq', 17), ('testimonials', 20), ('cta', 22), ('gallery', 25), ('document', 27)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('v1', 'Variant 1'), ('v2', 'Variant 2'), ('v3', 'Variant 3')], 'help_text': 'Select the layout variant for this block.'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('fade-left', 'Fade Left'), ('fade-right', 'Fade Right'), ('zoom-in', 'Zoom In')], 'help_text': 'Select the AOS animation effect.'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('image', 4), ('cta_text', 5), ('cta_link', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 9: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('content', 8), ('image', 4)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon name (e.g. from FontAwesome or similar)', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('icon', 10), ('name', 2), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('services', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('question', 2), ('answer', 8)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('items', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('quote', 11), ('author', 2), ('role', 5), ('image', 4)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('testimonials', 19)]], {}), 21: ('wagtail.blocks.URLBlock', (), {'required': True}), 22: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('button_text', 2), ('button_link', 21)]], {}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('images', 24)]], {}), 26: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': True}), 27: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('document', 26)]], {})}),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(blank=True, max_length=50, null=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
                ('menu', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='pages.menu')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('clean_name', models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name')),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma or new line separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.TextField(blank=True, help_text='Default value. Comma or new line separated values supported for checkboxes.', verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='pages.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
