# Generated by Django 4.2.28 on 2026-02-12 08:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('pages', '0003_alter_contactpage_intro_alter_contentpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('cta', 8), ('lead_magnet', 12)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('v1', 'Variant 1'), ('v2', 'Variant 2'), ('v3', 'Variant 3')], 'help_text': 'Select the layout variant for this block.'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('fade-left', 'Fade Left'), ('fade-right', 'Fade Right'), ('zoom-in', 'Zoom In')], 'help_text': 'Select the AOS animation effect.'}), 5: ('wagtail.blocks.CharBlock', (), {'required': True}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('variant', 3), ('animation', 4), ('title', 5), ('subtitle', 6), ('button_text', 5), ('button_link', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Download Free Guide', 'required': True}), 10: ('wagtail.blocks.URLBlock', (), {'required': False}), 11: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 12: ('wagtail.blocks.StructBlock', [[('variant', 3), ('animation', 4), ('title', 5), ('subtitle', 6), ('offer_text', 9), ('form_action', 10), ('image', 11)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceAreaIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceAreaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('location_name', models.CharField(max_length=100)),
                ('body', wagtail.fields.StreamField([('hero', 9), ('services', 16), ('success_stories', 19), ('cta', 21)], block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('v1', 'Variant 1'), ('v2', 'Variant 2'), ('v3', 'Variant 3')], 'help_text': 'Select the layout variant for this block.'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'None'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('fade-left', 'Fade Left'), ('fade-right', 'Fade Right'), ('zoom-in', 'Zoom In')], 'help_text': 'Select the AOS animation effect.'}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Primary CTA Text', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'label': 'Primary CTA Link', 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'label': 'Secondary CTA Text (e.g. Call Us)', 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'label': 'Secondary CTA Link (e.g. tel:123)', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('image', 4), ('cta_text', 5), ('cta_link', 6), ('secondary_cta_text', 7), ('secondary_cta_link', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Icon name (e.g. from FontAwesome)', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.CharBlock', (), {'default': 'Learn More', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('icon', 10), ('name', 2), ('description', 11), ('cta_text', 12), ('link', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('services', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('client_name', 2), ('story_title', 2), ('summary', 11), ('image', 4), ('link', 13)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('stories', 18)]], {}), 20: ('wagtail.blocks.URLBlock', (), {'required': True}), 21: ('wagtail.blocks.StructBlock', [[('variant', 0), ('animation', 1), ('title', 2), ('subtitle', 3), ('button_text', 2), ('button_link', 20)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='address',
            field=models.TextField(blank=True, help_text='Physical address for the map section'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='Google Maps Embed URL'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='phone_cta',
            field=models.CharField(blank=True, help_text="Phone number for 'Call Now' CTA", max_length=20),
        ),
    ]
