# Generated by Django 4.2.28 on 2026-02-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_blogpostpage_category_blogpostpage_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Blog Index Page'},
        ),
        migrations.AlterModelOptions(
            name='blogpostpage',
            options={'verbose_name': 'Blog Post Page'},
        ),
        migrations.AlterModelOptions(
            name='serviceareaindexpage',
            options={'verbose_name': 'Service Area Index Page'},
        ),
        migrations.AlterModelOptions(
            name='serviceareapage',
            options={'verbose_name': 'Service Area Page'},
        ),
    ]
