# Generated by Django 4.2.28 on 2026-02-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_blogindexpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Articles Index'},
        ),
        migrations.AlterModelOptions(
            name='blogpostpage',
            options={'verbose_name': 'Article Post'},
        ),
        migrations.AlterModelOptions(
            name='serviceareaindexpage',
            options={'verbose_name': 'Area Index Page'},
        ),
        migrations.AlterModelOptions(
            name='serviceareapage',
            options={'verbose_name': 'Area Detail Page'},
        ),
    ]
