# Generated by Django 4.2.28 on 2026-02-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('pages', '0007_alter_blogindexpage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_theme', models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('bold', 'Bold')], default='modern', max_length=20)),
                ('hero_variant', models.CharField(default='v1', max_length=10)),
                ('about_variant', models.CharField(default='v1', max_length=10)),
                ('services_variant', models.CharField(default='v1', max_length=10)),
                ('faq_variant', models.CharField(default='v1', max_length=10)),
                ('primary_color', models.CharField(default='#00D4FF', max_length=7)),
                ('secondary_color', models.CharField(default='#FF6B35', max_length=7)),
                ('background_color', models.CharField(default='#0A0E17', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('heading_font', models.CharField(default='Inter', max_length=100)),
                ('body_font', models.CharField(default='Inter', max_length=100)),
                ('animation_preset', models.CharField(default='smooth-fade', max_length=50)),
                ('last_ai_prompt', models.TextField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Theme Configuration',
            },
        ),
        migrations.DeleteModel(
            name='ThemeConfig',
        ),
    ]
