# Generated by Django 4.2.28 on 2026-02-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_blogindexpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_form_title',
            field=models.CharField(blank=True, default='Send Us a Message', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emergency_contact_label',
            field=models.CharField(blank=True, default='Emergency Contact', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='form_success_message',
            field=models.CharField(blank=True, default='Thank you! Your message has been sent successfully.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='gallery_tag',
            field=models.CharField(blank=True, default='Project Gallery', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='industries_tag',
            field=models.CharField(blank=True, default='Industries We Serve', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='no_results_message',
            field=models.CharField(blank=True, default='No items found. Please check back later.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='partners_tag',
            field=models.CharField(blank=True, default='Our Partners', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='process_tag',
            field=models.CharField(blank=True, default='Our Process', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='submit_button_label',
            field=models.CharField(blank=True, default='Submit Now', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='success_stories_tag',
            field=models.CharField(blank=True, default='Success Stories', max_length=50),
        ),
    ]
