# Generated by Django 4.2.28 on 2026-02-16 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('pages', '0011_sitesettings_call_us_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_icon',
            field=models.CharField(blank=True, default='fa-bell', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_icon',
            field=models.CharField(blank=True, default='fa-envelope', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='emergency_icon',
            field=models.CharField(blank=True, default='fa-shield-halved', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Site favicon (PNG or ICO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_icon',
            field=models.CharField(blank=True, default='fa-location-dot', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_icon',
            field=models.CharField(blank=True, default='fa-phone', max_length=50),
        ),
    ]
