# Generated by Django 4.2.28 on 2026-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_sitesettings_announcement_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_icon',
            field=models.CharField(blank=True, default='fa-bars', max_length=50),
        ),
    ]
