# Generated by Django 4.2.28 on 2026-02-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_sitesettings_menu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='base_theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('corporate', 'Corporate'), ('creative', 'Creative'), ('saas', 'SaaS'), ('editorial', 'Editorial')], default='modern', max_length=20),
        ),
    ]
