# Generated by Django 4.2.28 on 2026-02-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('pages', '0014_alter_themesettings_base_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themesettings',
            options={},
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Hero Background Image'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='hero_video_url',
            field=models.URLField(blank=True, help_text='Direct link to MP4 or YouTube/Vimeo URL', null=True, verbose_name='Hero Background Video'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Site Logo'),
        ),
        migrations.AddField(
            model_name='themesettings',
            name='site_name',
            field=models.CharField(blank=True, default='SecureGuard Pro', max_length=100),
        ),
    ]
