# Generated by Django 4.2.28 on 2026-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_themesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='base_theme',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('creative', 'Creative'), ('saas', 'SaaS'), ('editorial', 'Editorial')], default='corporate', max_length=20),
        ),
    ]
